easy_admin:
    site_name: 'Symfony-Bundles'
    design:
        brand_color: '#7ABA20'
        color_scheme: 'dark'
    list:
        title: 'List of %%entity_label%%'
        max_results: 50
    show:
        title: '%%entity_label%% (#%%entity_id%%)'
    search:
        title: 'Search in %%entity_label%%'
    entities:
        Package:
            class: App\Entity\Package
            label: 'Packages'
            list:
                fields: ['id', 'packageId', 'version', 'title', 'statInstalls', 'addedAt', 'updatedAt']
